### ISSUE TITLE
CLS Token not used

### ISSUE THREAD

**Issue by carhartt21** [kyegomez/Vit-RGTS#10]
Thanks for sharing the code and detailed documentation. 
I noticed that in the code the CLS token is created, but never used, because you hard coded mean pooling in the forward method. 
However, in the paper the CLS token is specifically mentioned in multiple places. 
Therefore I was wondering which pooling method you used in your experiments and what was the reasoning behind it. 

## Upvote & Fund

- We're using [Polar.sh](https://polar.sh/kyegomez) so you can upvote and help fund this issue.
- We receive the funding once the issue is completed & confirmed by you.
- Thank you in advance for helping prioritize & fund our backlog.

<a href="https://polar.sh/kyegomez/Vit-RGTS/issues/10">
<picture>
  <source media="(prefers-color-scheme: dark)" srcset="https://polar.sh/api/github/kyegomez/Vit-RGTS/issues/10/pledge.svg?darkmode=1">
  <img alt="Fund with Polar" src="https://polar.sh/api/github/kyegomez/Vit-RGTS/issues/10/pledge.svg">
</picture>
</a>

**Comment by QingSuML** [comment]
Looking forward to the author response to this issue.

**Comment by haribaskarsony** [comment]
> Thanks for sharing the code and detailed documentation. I noticed that in the code the CLS token is created, but never used, because you hard coded mean pooling in the forward method. However, in the paper the CLS token is specifically mentioned in multiple places. Therefore I was wondering which pooling method you used in your experiments and what was the reasoning behind it.
> 
> ## Upvote & Fund
> * We're using [Polar.sh](https://polar.sh/kyegomez) so you can upvote and help fund this issue.
> * We receive the funding once the issue is completed & confirmed by you.
> * Thank you in advance for helping prioritize & fund our backlog.
> 
> [ ![Fund with Polar](https://camo.githubusercontent.com/599f2a5b3febc339783090f619d367b4213fb6631d30cebcae2c80bdd1a9b3ef/68747470733a2f2f706f6c61722e73682f6170692f6769746875622f6b7965676f6d657a2f5669742d524754532f6973737565732f31302f706c656467652e737667) ](https://polar.sh/kyegomez/Vit-RGTS/issues/10)

@carhartt21 i was wondering the same. Were u able to figure out how the model initialization code needs to be modified according to the paper?
