### ISSUE TITLE
Attention  Map example

### ISSUE THREAD

**Issue by fedegonzal** [kyegomez/Vit-RGTS#7]
Hi, 

Since this repo is based on the paper "ViT needs registers" should be usefull to publish some example to visualize attention maps.

Thanks for this great work! 

## Upvote & Fund

- We're using [Polar.sh](https://polar.sh/kyegomez) so you can upvote and help fund this issue.
- We receive the funding once the issue is completed & confirmed by you.
- Thank you in advance for helping prioritize & fund our backlog.

<a href="https://polar.sh/kyegomez/Vit-RGTS/issues/7">
<picture>
  <source media="(prefers-color-scheme: dark)" srcset="https://polar.sh/api/github/kyegomez/Vit-RGTS/issues/7/pledge.svg?darkmode=1">
  <img alt="Fund with Polar" src="https://polar.sh/api/github/kyegomez/Vit-RGTS/issues/7/pledge.svg">
</picture>
</a>

**Comment by kyegomez** [comment]
@fedegonzal yes this would be a good idea, let's work together on this. Can you make an example?

**Comment by aronvandepol** [comment]
I'd also be very curious to see some examples! 🙌

**Comment by wylapp** [comment]
Hello everyone!

I managed to draw the attention map, and the artifacts do exist.

Other than the attention map, has anyone tried to draw the norms plot in Figure 3 (from "Vision Transformers Need Registers")? 
I got the opposite result, where there are **no outlier patches.** 
> We observe that an important difference between “artifact” patches and other patches is the norm of their token embedding at the output of the model.

This is the only sentence that authors explain what an outlier patch/token is. 

FYI, this is my implementation.
https://colab.research.google.com/drive/1gHDOi8RL8hHmfAJvF7IqyBF7tmosG0ko

![image](https://github.com/facebookresearch/dinov2/assets/11030493/b3330594-889a-44da-a9d6-dc8213ff4e18)

**Comment by zwyang6** [comment]
+1 demos are neccessary  🙌

**Comment by TumVink** [comment]
> Hello everyone!
> 
> I managed to draw the attention map, and the artifacts do exist.
> 
> Other than the attention map, has anyone tried to draw the norms plot in Figure 3 (from "Vision Transformers Need Registers")? I got the opposite result, where there are **no outlier patches.**
> 
> > We observe that an important difference between “artifact” patches and other patches is the norm of their token embedding at the output of the model.
> 
> This is the only sentence that authors explain what an outlier patch/token is.
> 
> FYI, this is my implementation. https://colab.research.google.com/drive/1gHDOi8RL8hHmfAJvF7IqyBF7tmosG0ko
> 
> ![image](https://private-user-images.githubusercontent.com/11030493/339337219-b3330594-889a-44da-a9d6-dc8213ff4e18.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjY1ODk3MzIsIm5iZiI6MTcyNjU4OTQzMiwicGF0aCI6Ii8xMTAzMDQ5My8zMzkzMzcyMTktYjMzMzA1OTQtODg5YS00NGRhLWE5ZDYtZGM4MjEzZmY0ZTE4LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA5MTclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwOTE3VDE2MTAzMlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTE0NTM4ZGEyYzU1YmEwYWVjZDA4OTc0NWU1YjhjNmY4YThiNzlkMTgwZjc1NmQ4OWUzNDE3ZDVkZDZlZDMyOWImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.kRP20QuGiiQpSbUYAMdSlk8C4hthIZ3znBiz57DX3zs)

Heyy, 
I am having a look at your script. Your attention_map seems good, however why L2 norm is based on Outputs[0]? Where does it come from?

**Comment by wylapp** [comment]
As aforementioned, the authors define the outlier patch as follows:

> We observe that an important difference between “artifact” patches and other patches is the norm of **their token embedding at the output of the model**.

The `output[0]` is the model's [last hidden state](https://huggingface.co/docs/transformers/model_doc/dinov2#transformers.Dinov2Model), which has the shape of `[Batch_size, Sequence_length, Embedding_size]`. I *think* this can be seen as the "token embedding at the output of the model". Then calculate the L2-norm in the last dimension using `torch.norm(outputs[0], 2, dim=-1)`.

**Comment by TumVink** [comment]
It makes sense! 
However, I re-produces the hign-norm outliers with the codes from [here](https://github.com/facebookresearch/dinov2/issues/373) with my own custom images.
